-- ============================================
-- WALL BALL MISSING DRILLS UPLOAD (FIXED)
-- ============================================
-- Inserts missing drills from CSV into wall_ball_drill_library
-- EXCLUDES drills that already exist (handles duplicates)
-- Generated: 2025-01-10
-- ============================================

-- First, let's update the existing "Behind the Back" drill with CSV data
UPDATE wall_ball_drill_library 
SET 
    difficulty_level = 2,
    description = 'Behind The Back wall ball drill (Difficulty: 2)',
    skill_focus = ARRAY['Master Fundamentals', 'Faking and Inside Finishing', 'Catch Everything', 'Advanced - Fun and Challenging']
WHERE drill_name = 'Behind the Back';

-- Now insert the truly missing drills (excluding exact matches and "Behind The Back")
INSERT INTO wall_ball_drill_library (
    drill_name,
    drill_slug,
    strong_hand_video_url,
    strong_hand_vimeo_id,
    off_hand_video_url,
    off_hand_vimeo_id,
    both_hands_video_url,
    both_hands_vimeo_id,
    difficulty_level,
    description,
    skill_focus,
    drill_type,
    equipment_needed,
    is_active
) VALUES
    (
        'Far Side Fake',
        'far-side-fake',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        'Far Side Fake wall ball drill (Difficulty: 1)',
        ARRAY['Master Fundamentals', 'Faking and Inside Finishing'],
        'Wall Ball',
        ARRAY['Wall', 'Lacrosse Ball', 'Lacrosse Stick'],
        true
    ),
    (
        'Leaner',
        'leaner',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        2,
        'Leaner wall ball drill (Difficulty: 2)',
        ARRAY['Faking and Inside Finishing', 'Shooting', 'Catch Everything', 'Advanced - Fun and Challenging'],
        'Wall Ball',
        ARRAY['Wall', 'Lacrosse Ball', 'Lacrosse Stick'],
        true
    ),
    (
        'Matt Brown Shooting',
        'matt-brown-shooting',
        'https://vimeo.com/997151121',
        '997151121',
        'https://vimeo.com/997151008',
        '997151008',
        NULL,
        NULL,
        1,
        'Matt Brown Shooting wall ball drill (Difficulty: 1)',
        ARRAY['Shooting', 'Defensive Emphasis'],
        'Wall Ball',
        ARRAY['Wall', 'Lacrosse Ball', 'Lacrosse Stick'],
        true
    ),
    (
        '80 % Over Hand',
        '80-over-hand',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        2,
        '80 % Over Hand wall ball drill (Difficulty: 2)',
        ARRAY['Shooting', 'Catch Everything'],
        'Wall Ball',
        ARRAY['Wall', 'Lacrosse Ball', 'Lacrosse Stick'],
        true
    ),
    (
        'Short Shot on the Run',
        'short-shot-on-the-run',
        NULL,
        NULL,
        NULL,
        NULL,
        'https://vimeo.com/997150867',
        '997150867',
        2,
        'Short Shot on the Run wall ball drill (Difficulty: 2)',
        ARRAY['Dodging', 'Shooting'],
        'Wall Ball',
        ARRAY['Wall', 'Lacrosse Ball', 'Lacrosse Stick'],
        true
    ),
    (
        'Up The Hash',
        'up-the-hash',
        'https://vimeo.com/997154935',
        '997154935',
        'https://vimeo.com/997154854',
        '997154854',
        NULL,
        NULL,
        2,
        'Up The Hash wall ball drill (Difficulty: 2)',
        ARRAY['Dodging', 'Shooting'],
        'Wall Ball',
        ARRAY['Wall', 'Lacrosse Ball', 'Lacrosse Stick'],
        true
    ),
    (
        'Criss Cross Quick Sticks',
        'criss-cross-quick-sticks',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        3,
        'Criss Cross Quick Sticks wall ball drill (Difficulty: 3)',
        ARRAY['Faking and Inside Finishing', 'Catch Everything', 'Advanced - Fun and Challenging'],
        'Wall Ball',
        ARRAY['Wall', 'Lacrosse Ball', 'Lacrosse Stick'],
        true
    ),
    (
        'Shovel Pass to Over The Shoulder',
        'shovel-pass-to-over-the-shoulder',
        'https://vimeo.com/997151416',
        '997151416',
        'https://vimeo.com/997151230',
        '997151230',
        NULL,
        NULL,
        2,
        'Shovel Pass to Over The Shoulder wall ball drill (Difficulty: 2)',
        ARRAY['Defensive Emphasis', 'Catch Everything', 'Advanced - Fun and Challenging'],
        'Wall Ball',
        ARRAY['Wall', 'Lacrosse Ball', 'Lacrosse Stick'],
        true
    ),
    (
        'Short Hop',
        'short-hop',
        'https://vimeo.com/997150674',
        '997150674',
        'https://vimeo.com/997150561',
        '997150561',
        NULL,
        NULL,
        2,
        'Short Hop wall ball drill (Difficulty: 2)',
        ARRAY['Defensive Emphasis', 'Catch Everything', 'Advanced - Fun and Challenging'],
        'Wall Ball',
        ARRAY['Wall', 'Lacrosse Ball', 'Lacrosse Stick'],
        true
    ),
    (
        'Side Arm to One Handed Extended Catch',
        'side-arm-to-one-handed-extended-catch',
        'https://vimeo.com/997152331',
        '997152331',
        'https://vimeo.com/997152086',
        '997152086',
        NULL,
        NULL,
        2,
        'Side Arm to One Handed Extended Catch wall ball drill (Difficulty: 2)',
        ARRAY['Catch Everything', 'Advanced - Fun and Challenging'],
        'Wall Ball',
        ARRAY['Wall', 'Lacrosse Ball', 'Lacrosse Stick'],
        true
    ),
    (
        '3 Step Up and Backs',
        '3-step-up-and-backs',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        2,
        '3 Step Up and Backs wall ball drill (Difficulty: 2)',
        ARRAY['Wall Ball'],
        'Wall Ball',
        ARRAY['Wall', 'Lacrosse Ball', 'Lacrosse Stick'],
        true
    ),
    (
        '80 % Side Arm',
        '80-side-arm',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        2,
        '80 % Side Arm wall ball drill (Difficulty: 2)',
        ARRAY['Shooting', 'Catch Everything'],
        'Wall Ball',
        ARRAY['Wall', 'Lacrosse Ball', 'Lacrosse Stick'],
        true
    ),
    (
        'Ankle Biters',
        'ankle-biters',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        2,
        'Ankle Biters wall ball drill (Difficulty: 2)',
        ARRAY['Defensive Emphasis', 'Catch Everything', 'Advanced - Fun and Challenging'],
        'Wall Ball',
        ARRAY['Wall', 'Lacrosse Ball', 'Lacrosse Stick'],
        true
    ),
    (
        'Around The World',
        'around-the-world',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        2,
        'Around The World wall ball drill (Difficulty: 2)',
        ARRAY['Faking and Inside Finishing', 'Catch Everything'],
        'Wall Ball',
        ARRAY['Wall', 'Lacrosse Ball', 'Lacrosse Stick'],
        true
    ),
    (
        'Bottom Hand Only',
        'bottom-hand-only',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        'Bottom Hand Only wall ball drill (Difficulty: 1)',
        ARRAY['Master Fundamentals', 'Conditioning', 'Shooting', 'Advanced - Fun and Challenging'],
        'Wall Ball',
        ARRAY['Wall', 'Lacrosse Ball', 'Lacrosse Stick'],
        true
    ),
    (
        'Canadian Cross Hand',
        'canadian-cross-hand',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        'Canadian Cross Hand wall ball drill (Difficulty: 1)',
        ARRAY['Faking and Inside Finishing', 'Shooting', 'Advanced - Fun and Challenging'],
        'Wall Ball',
        ARRAY['Wall', 'Lacrosse Ball', 'Lacrosse Stick'],
        true
    ),
    (
        'Catch and Hitch',
        'catch-and-hitch',
        NULL,
        NULL,
        NULL,
        NULL,
        'https://vimeo.com/997147689',
        '997147689',
        1,
        'Catch and Hitch wall ball drill (Difficulty: 1)',
        ARRAY['Dodging', 'Conditioning', 'Shooting'],
        'Wall Ball',
        ARRAY['Wall', 'Lacrosse Ball', 'Lacrosse Stick'],
        true
    ),
    (
        'Face Dodge Shovel Pass',
        'face-dodge-shovel-pass',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        2,
        'Face Dodge Shovel Pass wall ball drill (Difficulty: 2)',
        ARRAY['Master Fundamentals', 'Dodging', 'Defensive Emphasis'],
        'Wall Ball',
        ARRAY['Wall', 'Lacrosse Ball', 'Lacrosse Stick'],
        true
    ),
    (
        'Far Near Far Finish',
        'far-near-far-finish',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        'Far Near Far Finish wall ball drill (Difficulty: 1)',
        ARRAY['Faking and Inside Finishing'],
        'Wall Ball',
        ARRAY['Wall', 'Lacrosse Ball', 'Lacrosse Stick'],
        true
    ),
    (
        'Figure 8 - Down The Middle',
        'figure-8-down-the-middle',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        'Figure 8 - Down The Middle wall ball drill (Difficulty: 1)',
        ARRAY['Conditioning', 'Defensive Emphasis'],
        'Wall Ball',
        ARRAY['Wall', 'Lacrosse Ball', 'Lacrosse Stick'],
        true
    ),
    (
        'Figure 8 - Up The Middle',
        'figure-8-up-the-middle',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        'Figure 8 - Up The Middle wall ball drill (Difficulty: 1)',
        ARRAY['Conditioning', 'Defensive Emphasis'],
        'Wall Ball',
        ARRAY['Wall', 'Lacrosse Ball', 'Lacrosse Stick'],
        true
    ),
    (
        'Figure 8 Ground Balls',
        'figure-8-ground-balls',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        'Figure 8 Ground Balls wall ball drill (Difficulty: 1)',
        ARRAY['Master Fundamentals', 'Conditioning', 'Defensive Emphasis'],
        'Wall Ball',
        ARRAY['Wall', 'Lacrosse Ball', 'Lacrosse Stick'],
        true
    ),
    (
        'Jump Shot',
        'jump-shot',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        2,
        'Jump Shot wall ball drill (Difficulty: 2)',
        ARRAY['Dodging', 'Shooting'],
        'Wall Ball',
        ARRAY['Wall', 'Lacrosse Ball', 'Lacrosse Stick'],
        true
    ),
    (
        'Lever Pass',
        'lever-pass',
        'https://vimeo.com/997150608',
        '997150608',
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        'Lever Pass wall ball drill (Difficulty: 1)',
        ARRAY['Dodging', 'Faking and Inside Finishing', 'Defensive Emphasis', 'Advanced - Fun and Challenging'],
        'Wall Ball',
        ARRAY['Wall', 'Lacrosse Ball', 'Lacrosse Stick'],
        true
    ),
    (
        'Look Back Fake',
        'look-back-fake',
        'https://vimeo.com/997150871',
        '997150871',
        'https://vimeo.com/997150734',
        '997150734',
        NULL,
        NULL,
        1,
        'Look Back Fake wall ball drill (Difficulty: 1)',
        ARRAY['Dodging', 'Faking and Inside Finishing', 'Defensive Emphasis'],
        'Wall Ball',
        ARRAY['Wall', 'Lacrosse Ball', 'Lacrosse Stick'],
        true
    ),
    (
        'Near Far Finish',
        'near-far-finish',
        'https://vimeo.com/997151360',
        '997151360',
        'https://vimeo.com/997151296',
        '997151296',
        NULL,
        NULL,
        1,
        'Near Far Finish wall ball drill (Difficulty: 1)',
        ARRAY['Faking and Inside Finishing'],
        'Wall Ball',
        ARRAY['Wall', 'Lacrosse Ball', 'Lacrosse Stick'],
        true
    ),
    (
        'Off Stick Side Catch',
        'off-stick-side-catch',
        'https://vimeo.com/997151947',
        '997151947',
        'https://vimeo.com/997151891',
        '997151891',
        NULL,
        NULL,
        1,
        'Off Stick Side Catch wall ball drill (Difficulty: 1)',
        ARRAY['Master Fundamentals', 'Faking and Inside Finishing', 'Shooting', 'Defensive Emphasis', 'Catch Everything'],
        'Wall Ball',
        ARRAY['Wall', 'Lacrosse Ball', 'Lacrosse Stick'],
        true
    ),
    (
        'Pop to Pass and Catch',
        'pop-to-pass-and-catch',
        NULL,
        NULL,
        NULL,
        NULL,
        'https://vimeo.com/997152579',
        '997152579',
        1,
        'Pop to Pass and Catch wall ball drill (Difficulty: 1)',
        ARRAY['Master Fundamentals', 'Dodging', 'Conditioning', 'Catch Everything'],
        'Wall Ball',
        ARRAY['Wall', 'Lacrosse Ball', 'Lacrosse Stick'],
        true
    ),
    (
        'Question Mark',
        'question-mark',
        'https://vimeo.com/997153218',
        '997153218',
        'https://vimeo.com/997153032',
        '997153032',
        'https://vimeo.com/997152824',
        '997152824',
        1,
        'Question Mark wall ball drill (Difficulty: 1)',
        ARRAY['Master Fundamentals', 'Dodging', 'Defensive Emphasis'],
        'Wall Ball',
        ARRAY['Wall', 'Lacrosse Ball', 'Lacrosse Stick'],
        true
    ),
    (
        'Roll Dodge Chin to Shoulder',
        'roll-dodge-chin-to-shoulder',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        2,
        'Roll Dodge Chin to Shoulder wall ball drill (Difficulty: 2)',
        ARRAY['Dodging', 'Conditioning'],
        'Wall Ball',
        ARRAY['Wall', 'Lacrosse Ball', 'Lacrosse Stick'],
        true
    ),
    (
        'Side Arm',
        'side-arm',
        'https://vimeo.com/997151690',
        '997151690',
        'https://vimeo.com/997151493',
        '997151493',
        NULL,
        NULL,
        1,
        'Side Arm wall ball drill (Difficulty: 1)',
        ARRAY['Master Fundamentals', 'Shooting', 'Catch Everything'],
        'Wall Ball',
        ARRAY['Wall', 'Lacrosse Ball', 'Lacrosse Stick'],
        true
    ),
    (
        'Split to Jump Shot',
        'split-to-jump-shot',
        'https://vimeo.com/997152904',
        '997152904',
        'https://vimeo.com/997152973',
        '997152973',
        'https://vimeo.com/997152572',
        '997152572',
        2,
        'Split to Jump Shot wall ball drill (Difficulty: 2)',
        ARRAY['Dodging', 'Conditioning', 'Shooting'],
        'Wall Ball',
        ARRAY['Wall', 'Lacrosse Ball', 'Lacrosse Stick'],
        true
    ),
    (
        'Step Back Throw Back',
        'step-back-throw-back',
        'https://vimeo.com/997153635',
        '997153635',
        'https://vimeo.com/997153515',
        '997153515',
        'https://vimeo.com/997153322',
        '997153322',
        1,
        'Step Back Throw Back wall ball drill (Difficulty: 1)',
        ARRAY['Dodging'],
        'Wall Ball',
        ARRAY['Wall', 'Lacrosse Ball', 'Lacrosse Stick'],
        true
    ),
    (
        'Three Steps Up and Back',
        'three-steps-up-and-back',
        NULL,
        NULL,
        'https://vimeo.com/997153712',
        '997153712',
        NULL,
        NULL,
        2,
        'Three Steps Up and Back wall ball drill (Difficulty: 2)',
        ARRAY['Master Fundamentals', 'Conditioning', 'Defensive Emphasis'],
        'Wall Ball',
        ARRAY['Wall', 'Lacrosse Ball', 'Lacrosse Stick'],
        true
    ),
    (
        'Top Hand Only',
        'top-hand-only',
        'https://vimeo.com/997153985',
        '997153985',
        'https://vimeo.com/997153886',
        '997153886',
        NULL,
        NULL,
        1,
        'Top Hand Only wall ball drill (Difficulty: 1)',
        ARRAY['Master Fundamentals', 'Conditioning', 'Shooting', 'Advanced - Fun and Challenging'],
        'Wall Ball',
        ARRAY['Wall', 'Lacrosse Ball', 'Lacrosse Stick'],
        true
    ),
    (
        'Underhand Behind The Back',
        'underhand-behind-the-back',
        'https://vimeo.com/997154661',
        '997154661',
        'https://vimeo.com/997154577',
        '997154577',
        NULL,
        NULL,
        3,
        'Underhand Behind The Back wall ball drill (Difficulty: 3)',
        ARRAY['Advanced - Fun and Challenging'],
        'Wall Ball',
        ARRAY['Wall', 'Lacrosse Ball', 'Lacrosse Stick'],
        true
    ),
    (
        'Underhand Between The Legs',
        'underhand-between-the-legs',
        'https://vimeo.com/997154784',
        '997154784',
        'https://vimeo.com/997154725',
        '997154725',
        NULL,
        NULL,
        3,
        'Underhand Between The Legs wall ball drill (Difficulty: 3)',
        ARRAY['Advanced - Fun and Challenging'],
        'Wall Ball',
        ARRAY['Wall', 'Lacrosse Ball', 'Lacrosse Stick'],
        true
    ),
    (
        'Walk The Dog Pass',
        'walk-the-dog-pass',
        'https://vimeo.com/997155081',
        '997155081',
        'https://vimeo.com/997155010',
        '997155010',
        NULL,
        NULL,
        3,
        'Walk The Dog Pass wall ball drill (Difficulty: 3)',
        ARRAY['Dodging', 'Conditioning', 'Advanced - Fun and Challenging'],
        'Wall Ball',
        ARRAY['Wall', 'Lacrosse Ball', 'Lacrosse Stick'],
        true
    ),
    (
        'Walk The Dog to Wrister',
        'walk-the-dog-to-wrister',
        'https://vimeo.com/997155211',
        '997155211',
        'https://vimeo.com/997155147',
        '997155147',
        NULL,
        NULL,
        3,
        'Walk The Dog to Wrister wall ball drill (Difficulty: 3)',
        ARRAY['Dodging', 'Conditioning', 'Shooting', 'Defensive Emphasis', 'Advanced - Fun and Challenging'],
        'Wall Ball',
        ARRAY['Wall', 'Lacrosse Ball', 'Lacrosse Stick'],
        true
    );

-- Continue with remaining drills that need unique handling
INSERT INTO wall_ball_drill_library (
    drill_name,
    drill_slug,
    strong_hand_video_url,
    strong_hand_vimeo_id,
    off_hand_video_url,
    off_hand_vimeo_id,
    both_hands_video_url,
    both_hands_vimeo_id,
    difficulty_level,
    description,
    skill_focus,
    drill_type,
    equipment_needed,
    is_active
) VALUES
    (
        'Around The World (Variant)',
        'around-the-world-variant',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        2,
        'Around The World variant wall ball drill (Difficulty: 2)',
        ARRAY['Catch Everything'],
        'Wall Ball',
        ARRAY['Wall', 'Lacrosse Ball', 'Lacrosse Stick'],
        true
    );

-- ============================================
-- VERIFICATION QUERIES
-- ============================================

-- Check total drills after insert
SELECT COUNT(*) as total_drills FROM wall_ball_drill_library;

-- Check newly inserted drills
SELECT id, drill_name, difficulty_level, 
       CASE 
           WHEN strong_hand_vimeo_id IS NOT NULL THEN 'Has Strong Hand Video'
           ELSE 'No Strong Hand Video'
       END as strong_hand_status,
       CASE 
           WHEN off_hand_vimeo_id IS NOT NULL THEN 'Has Off Hand Video'
           ELSE 'No Off Hand Video'
       END as off_hand_status,
       CASE 
           WHEN both_hands_vimeo_id IS NOT NULL THEN 'Has Both Hands Video'
           ELSE 'No Both Hands Video'
       END as both_hands_status
FROM wall_ball_drill_library 
WHERE id > 9  -- Assuming current max ID is 9
ORDER BY difficulty_level, drill_name;

-- Check for any remaining duplicates
SELECT drill_name, COUNT(*) as count
FROM wall_ball_drill_library
GROUP BY drill_name
HAVING COUNT(*) > 1;
