-- Populate drill_ids arrays in skills_academy_workouts
-- Generated from CSV drill-workout mapping analysis
-- Generated: 2025-01-15

-- Create temporary mapping table
CREATE TEMP TABLE drill_workout_mapping (
    drill_name TEXT,
    workout_name TEXT,
    sequence_order INTEGER
);

-- Insert all drill-workout mappings
INSERT INTO drill_workout_mapping (drill_name, workout_name, sequence_order) VALUES
('Overhand', 'Master Fundamentals', 1),
('Overhand', '10 Master Fund', 1),
('Overhand', '5 Minute Master Fundamentals', 1),
('Overhand', 'Dodging', 1),
('Overhand', 'Conditioning', 1),
('Overhand', '10 Min Conditioning', 1),
('Overhand', 'Faking and Inside Finishing', 1),
('Overhand', '10 Min Faking', 1),
('Overhand', 'Shooting', 1),
('Overhand', '10 Shooting', 1),
('Overhand', '5 Shooting', 1),
('Overhand', 'Defensive Emphasis', 1),
('Overhand', '10 Defense', 1),
('Overhand', '5 Defense', 1),
('Overhand', 'Catch Everything', 1),
('Overhand', '10 Catch Everything', 1),
('Quick Sticks', 'Master Fundamentals', 2),
('Quick Sticks', '10 Master Fund', 2),
('Quick Sticks', '5 Minute Master Fundamentals', 2),
('Quick Sticks', 'Conditioning', 2),
('Quick Sticks', '10 Min Conditioning', 2),
('Quick Sticks', 'Faking and Inside Finishing', 2),
('Quick Sticks', '10 Min Faking', 2),
('Quick Sticks', 'Shooting', 2),
('Quick Sticks', '10 Shooting', 2),
('Quick Sticks', 'Catch Everything', 2),
('Quick Sticks', '10 Catch Everything', 2),
('Quick Sticks', '5 Catch Everything', 1),
('Quick Sticks', 'Advanced - Fun and Challenging', 1),
('Quick Sticks', '10 Catch Everything', 1),
('Turned Right', 'Master Fundamentals', 9),
('Turned Right', '5 Minute Master Fundamentals', 3),
('Turned Right', 'Defensive Emphasis', 4),
('Turned Right', '10 Defense', 4),
('Turned Right', 'Catch Everything', 4),
('Turned Right', '10 Catch Everything', 4),
('Turned Right', '5 Catch Everything', 3),
('Turned Left', 'Master Fundamentals', 8),
('Turned Left', '5 Minute Master Fundamentals', 4),
('Turned Left', 'Defensive Emphasis', 3),
('Turned Left', '10 Defense', 3),
('Turned Left', 'Catch Everything', 3),
('Turned Left', '10 Catch Everything', 3),
('Turned Left', '5 Catch Everything', 2),
('Catch and Switch', 'Master Fundamentals', 10),
('Catch and Switch', '10 Master Fund', 6),
('Catch and Switch', '5 Minute Master Fundamentals', 5),
('Catch and Switch', 'Dodging', 2),
('Catch and Switch', '10 Dodging', 1),
('Catch and Switch', '5 Dodging', 1),
('Twister', 'Faking and Inside Finishing', 6),
('Twister', '10 Min Faking', 4),
('Twister', '5 Minute Faking', 1),
('Twister', 'Shooting', 17),
('Twister', '10 Shooting', 10),
('Twister', 'Advanced - Fun and Challenging', 7),
('Twister', '10 Catch Everything', 4),
('Near Side Fake', 'Master Fundamentals', 3),
('Near Side Fake', '10 Master Fund', 3),
('Near Side Fake', 'Faking and Inside Finishing', 9),
('Near Side Fake', '10 Min Faking', 6),
('Near Side Fake', '5 Minute Faking', 2),
('Far Side Fake', 'Master Fundamentals', 4),
('Far Side Fake', '10 Master Fund', 4),
('Far Side Fake', 'Faking and Inside Finishing', 11),
('Far Side Fake', '10 Min Faking', 7),
('Far Side Fake', '5 Minute Faking', 3),
('Behind The Back', 'Master Fundamentals', 15),
('Behind The Back', 'Faking and Inside Finishing', 13),
('Behind The Back', '10 Min Faking', 8),
('Behind The Back', '5 Minute Faking', 4),
('Behind The Back', 'Advanced - Fun and Challenging', 5),
('Behind The Back', '10 Catch Everything', 2),
('Leaner', 'Faking and Inside Finishing', 15),
('Leaner', '10 Min Faking', 10),
('Leaner', '5 Minute Faking', 5),
('Leaner', 'Shooting', 18),
('Leaner', 'Advanced - Fun and Challenging', 10),
('Leaner', '10 Catch Everything', 7),
('Leaner', '5 Catch Everything', 2),
('Matt Brown Shooting', 'Shooting', 3),
('Matt Brown Shooting', '10 Shooting', 3),
('Matt Brown Shooting', '5 Shooting', 2),
('Matt Brown Shooting', 'Defensive Emphasis', 9),
('80 % Over Hand', 'Shooting', 9),
('80 % Over Hand', '10 Shooting', 5),
('80 % Over Hand', '5 Shooting', 3),
('80 % Over Hand', 'Catch Everything', 10),
('Short Shot on the Run', 'Dodging', 12),
('Short Shot on the Run', 'Shooting', 11),
('Short Shot on the Run', '10 Shooting', 7),
('Short Shot on the Run', '5 Shooting', 4),
('Up The Hash', 'Dodging', 13),
('Up The Hash', 'Shooting', 12),
('Up The Hash', '10 Shooting', 8),
('Up The Hash', '5 Shooting', 5),
('Criss Cross Quick Sticks', 'Faking and Inside Finishing', 8),
('Criss Cross Quick Sticks', 'Catch Everything', 6),
('Criss Cross Quick Sticks', '10 Catch Everything', 6),
('Criss Cross Quick Sticks', 'Advanced - Fun and Challenging', 9),
('Criss Cross Quick Sticks', '10 Catch Everything', 6),
('Criss Cross Quick Sticks', '5 Catch Everything', 1),
('Shovel Pass to Over The Shoulder', 'Defensive Emphasis', 12),
('Shovel Pass to Over The Shoulder', '10 Defense', 10),
('Shovel Pass to Over The Shoulder', 'Catch Everything', 7),
('Shovel Pass to Over The Shoulder', '10 Catch Everything', 7),
('Shovel Pass to Over The Shoulder', 'Advanced - Fun and Challenging', 11),
('Shovel Pass to Over The Shoulder', '10 Catch Everything', 8),
('Shovel Pass to Over The Shoulder', '5 Catch Everything', 3),
('Short Hop', 'Defensive Emphasis', 17),
('Short Hop', 'Catch Everything', 13),
('Short Hop', '10 Catch Everything', 10),
('Short Hop', 'Advanced - Fun and Challenging', 13),
('Short Hop', '10 Catch Everything', 9),
('Short Hop', '5 Catch Everything', 4),
('Side Arm to One Handed Extended Catch', 'Catch Everything', 14),
('Side Arm to One Handed Extended Catch', 'Advanced - Fun and Challenging', 14),
('Side Arm to One Handed Extended Catch', '10 Catch Everything', 10),
('Side Arm to One Handed Extended Catch', '5 Catch Everything', 5),
('80 % Side Arm', 'Shooting', 10),
('80 % Side Arm', '10 Shooting', 6),
('80 % Side Arm', 'Catch Everything', 11),
('Ankle Biters', 'Defensive Emphasis', 16),
('Ankle Biters', 'Catch Everything', 12),
('Ankle Biters', '10 Catch Everything', 9),
('Ankle Biters', 'Advanced - Fun and Challenging', 12),
('Around The World', 'Faking and Inside Finishing', 14),
('Around The World', '10 Min Faking', 9),
('Around The World', 'Advanced - Fun and Challenging', 6),
('Around The World', '10 Catch Everything', 3),
('Bottom Hand Only', 'Master Fundamentals', 6),
('Bottom Hand Only', 'Conditioning', 4),
('Bottom Hand Only', 'Shooting', 5),
('Bottom Hand Only', 'Advanced - Fun and Challenging', 3),
('Canadian Cross Hand', 'Faking and Inside Finishing', 3),
('Canadian Cross Hand', 'Shooting', 6),
('Canadian Cross Hand', 'Advanced - Fun and Challenging', 4),
('Catch and Hitch', 'Dodging', 7),
('Catch and Hitch', '10 Dodging', 6),
('Catch and Hitch', '5 Dodging', 6),
('Catch and Hitch', 'Conditioning', 10),
('Catch and Hitch', '10 Min Conditioning', 8),
('Catch and Hitch', 'Shooting', 13),
('Face Dodge Shovel Pass', 'Master Fundamentals', 12),
('Face Dodge Shovel Pass', '10 Master Fund', 7),
('Face Dodge Shovel Pass', 'Dodging', 3),
('Face Dodge Shovel Pass', '10 Dodging', 2),
('Face Dodge Shovel Pass', '5 Dodging', 2),
('Face Dodge Shovel Pass', 'Defensive Emphasis', 5),
('Face Dodge Shovel Pass', '10 Defense', 5),
('Face Dodge Shovel Pass', '5 Defense', 2),
('Far Near Far Finish', 'Faking and Inside Finishing', 12),
('Figure 8 - Down The Middle', 'Conditioning', 8),
('Figure 8 - Down The Middle', '10 Min Conditioning', 6),
('Figure 8 - Down The Middle', '5 Min Conditioning', 4),
('Figure 8 - Down The Middle', 'Defensive Emphasis', 14),
('Figure 8 - Up The Middle', 'Conditioning', 8),
('Figure 8 - Up The Middle', '10 Min Conditioning', 7),
('Figure 8 - Up The Middle', '5 Min Conditioning', 5),
('Figure 8 - Up The Middle', 'Defensive Emphasis', 15),
('Figure 8 Ground Balls', 'Master Fundamentals', 14),
('Figure 8 Ground Balls', '10 Master Fund', 8),
('Figure 8 Ground Balls', 'Conditioning', 7),
('Figure 8 Ground Balls', '10 Min Conditioning', 5),
('Figure 8 Ground Balls', '5 Min Conditioning', 3),
('Figure 8 Ground Balls', 'Defensive Emphasis', 8),
('Figure 8 Ground Balls', '10 Defense', 7),
('Figure 8 Ground Balls', '5 Defense', 4),
('Jump Shot', 'Dodging', 10),
('Jump Shot', 'Shooting', 14),
('Jump Shot', '10 Shooting', 9),
('Lever Pass', 'Dodging', 8),
('Lever Pass', '10 Dodging', 7),
('Lever Pass', 'Faking and Inside Finishing', 7),
('Lever Pass', '10 Min Faking', 5),
('Lever Pass', 'Defensive Emphasis', 13),
('Lever Pass', 'Advanced - Fun and Challenging', 8),
('Lever Pass', '10 Catch Everything', 5),
('Look Back Fake', 'Dodging', 9),
('Look Back Fake', '10 Dodging', 8),
('Look Back Fake', 'Faking and Inside Finishing', 5),
('Look Back Fake', 'Defensive Emphasis', 6),
('Look Back Fake', '10 Defense', 6),
('Look Back Fake', '5 Defense', 3),
('Near Far Finish', 'Faking and Inside Finishing', 10),
('Off Stick Side Catch', 'Master Fundamentals', 7),
('Off Stick Side Catch', '10 Master Fund', 5),
('Off Stick Side Catch', 'Faking and Inside Finishing', 4),
('Off Stick Side Catch', '10 Min Faking', 3),
('Off Stick Side Catch', 'Shooting', 7),
('Off Stick Side Catch', 'Defensive Emphasis', 2),
('Off Stick Side Catch', '10 Defense', 2),
('Off Stick Side Catch', 'Catch Everything', 5),
('Off Stick Side Catch', '10 Catch Everything', 5),
('Off Stick Side Catch', '5 Catch Everything', 4),
('Pop to Pass and Catch', 'Master Fundamentals', 16),
('Pop to Pass and Catch', '10 Master Fund', 9),
('Pop to Pass and Catch', 'Dodging', 4),
('Pop to Pass and Catch', '10 Dodging', 3),
('Pop to Pass and Catch', 'Conditioning', 6),
('Pop to Pass and Catch', '10 Min Conditioning', 4),
('Pop to Pass and Catch', '5 Min Conditioning', 2),
('Pop to Pass and Catch', 'Catch Everything', 9),
('Pop to Pass and Catch', '10 Catch Everything', 8),
('Pop to Pass and Catch', '5 Catch Everything', 5),
('Question Mark', 'Master Fundamentals', 17),
('Question Mark', '10 Master Fund', 10),
('Question Mark', 'Dodging', 5),
('Question Mark', '10 Dodging', 4),
('Question Mark', 'Defensive Emphasis', 10),
('Question Mark', '10 Defense', 8),
('Question Mark', '5 Defense', 5),
('Roll Dodge Chin to Shoulder', 'Dodging', 14),
('Roll Dodge Chin to Shoulder', '10 Dodging', 10),
('Roll Dodge Chin to Shoulder', '5 Dodging', 10),
('Roll Dodge Chin to Shoulder', 'Conditioning', 13),
('Roll Dodge Chin to Shoulder', '10 Min Conditioning', 9),
('Side Arm', 'Master Fundamentals', 11),
('Side Arm', 'Shooting', 8),
('Side Arm', '10 Shooting', 4),
('Side Arm', 'Catch Everything', 8),
('Split to Jump Shot', 'Dodging', 11),
('Split to Jump Shot', '10 Dodging', 9),
('Split to Jump Shot', 'Conditioning', 14),
('Split to Jump Shot', '10 Min Conditioning', 10),
('Split to Jump Shot', 'Shooting', 15),
('Step Back Throw Back', 'Dodging', 6),
('Step Back Throw Back', '10 Dodging', 5),
('Step Back Throw Back', '5 Dodging', 5),
('Three Steps Up and Back', 'Master Fundamentals', 13),
('Three Steps Up and Back', 'Conditioning', 5),
('Three Steps Up and Back', '10 Min Conditioning', 3),
('Three Steps Up and Back', '5 Min Conditioning', 1),
('Three Steps Up and Back', 'Defensive Emphasis', 7),
('Top Hand Only', 'Master Fundamentals', 5),
('Top Hand Only', 'Conditioning', 3),
('Top Hand Only', 'Shooting', 4),
('Top Hand Only', 'Advanced - Fun and Challenging', 2),
('Underhand Behind The Back', 'Advanced - Fun and Challenging', 17),
('Underhand Between The Legs', 'Advanced - Fun and Challenging', 18),
('Walk The Dog Pass', 'Dodging', 16),
('Walk The Dog Pass', 'Conditioning', 12),
('Walk The Dog Pass', 'Advanced - Fun and Challenging', 16),
('Walk The Dog to Wrister', 'Dodging', 15),
('Walk The Dog to Wrister', 'Conditioning', 11),
('Walk The Dog to Wrister', 'Shooting', 16),
('Walk The Dog to Wrister', 'Defensive Emphasis', 11),
('Walk The Dog to Wrister', '10 Defense', 9),
('Walk The Dog to Wrister', 'Advanced - Fun and Challenging', 15),
('Foot Fire Single Jab Face Dodge to Answer Move', 'Midfield 10', 14),
('Foot Fire Single Jab Face Dodge to Answer Move', 'Midfield 8', 12),
('Foot Fire Single Jab Face Dodge to Roll Back Drill', 'Midfield 10', 13),
('Foot Fire Single Jab Face Dodge to Roll Back Drill', 'Midfield 9', 13),
('Foot Fire Single Jab Face Dodge to Roll Back Drill', 'Midfield 6', 15),
('Up to Pass Face Dodge Drill', 'Midfield 1', 16),
('Wind Up Face Dodge to Shin Cradles', 'Midfield 10', 9),
('Wind Up Face Dodge to Shin Cradles', 'Midfield 1', 15),
('Wind Up Face Dodge to Shot Drill', 'Midfield 10', 11),
('Wind Up Face Dodge to Shot Drill', 'Midfield 6', 12),
('Wind Up Face Dodge to Shot Drill', 'Midfield 5', 8),
('Wind Up Face Dodge to Shot Drill', 'Midfield 1', 17),
('“Talk To - Listen To” Top Hand Fake Drill', 'Midfield 3', 9),
('Bottom Hand Fake Drill', 'Midfield 3', 10),
('Fake Far Finish Near Drill', 'Midfield 10', 7),
('Fake Far Finish Near Drill', 'Midfield 9', 5),
('Fake Near Finish Far Drill', 'Midfield 10', 5),
('Fake Near Finish Far Drill', 'Midfield 9', 3),
('Fake The Slide Away Dodging Drill', 'Midfield 7', 15),
('Far Side Fake Drill', 'Midfield 10', 6),
('Far Side Fake Drill', 'Midfield 9', 4),
('Far Side Fake Drill', 'Midfield 3', 12),
('Near Side Fake Drill', 'Midfield 10', 4),
('Near Side Fake Drill', 'Midfield 9', 2),
('Near Side Fake Drill', 'Midfield 3', 11),
('Up The Hash - Lever Shot Drill', 'Midfield 9', 12),
('Minnows Ground Ball Drill, Miss, Kick, Scoop', 'Midfield 1', 7),
('Minnows Ground Balls, Kiss The Stick Up to Pass Drill', 'Midfield 1', 6),
('Off Hand Wide Turn Ground Balls', 'Midfield 10', 2),
('Off Hand Wide Turn Ground Balls', 'Midfield 8', 2),
('Off Hand Wide Turn Ground Balls', 'Midfield 7', 2),
('Off Hand Wide Turn Ground Balls', 'Midfield 4', 2),
('Off Hand Wide Turn Ground Balls', 'Midfield 3', 2),
('Off Hand Wide Turn Ground Balls', 'Midfield 1', 14),
('Strong Hand Wide Turn Ground Balls', 'Midfield 10', 1),
('Strong Hand Wide Turn Ground Balls', 'Midfield 8', 1),
('Strong Hand Wide Turn Ground Balls', 'Midfield 7', 1),
('Strong Hand Wide Turn Ground Balls', 'Midfield 4', 1),
('Strong Hand Wide Turn Ground Balls', 'Midfield 3', 1),
('Strong Hand Wide Turn Ground Balls', 'Midfield 1', 12),
('Back Foot Hitch Drill', 'Midfield 6', 8),
('Double Hitch Drill', 'Midfield 6', 11),
('Front Foot Hitch Drill', 'Midfield 8', 13),
('Front Foot Hitch Drill', 'Midfield 6', 7),
('Front Foot Hitch Drill', 'Midfield 5', 9),
('Front Foot Hitch Drill', 'Midfield 2', 15),
('Pop to Hitch Drill', 'Midfield 6', 10),
('4 Cone - Infinity Close The Gate Drill', 'Midfield 4', 5),
('4 Cone - Infinity Drop Step and Run Drill', 'Midfield 4', 6),
('4 Cone - Infinity Drop Step and Shuffle Drill', 'Midfield 4', 4),
('4 Cone - Side Shuffle Drill', 'Midfield 4', 3),
('Approach and Recover Clockwise - Side Left', 'Midfield 4', 14),
('Approach and Recover Clockwise - Side Right', 'Midfield 12', 6),
('Approach and Recover Clockwise - Side Right', 'Midfield 4', 12),
('Approach and Recover Clockwise - Top Left', 'Midfield 8', 9),
('Approach and Recover Clockwise - Top Right', 'Midfield 12', 7),
('Approach and Recover Clockwise - Top Right', 'Midfield 8', 8),
('Approach and Recover Counter Clockwise - Side Left', 'Midfield 4', 15),
('Approach and Recover Counter Clockwise - Side Right', 'Midfield 4', 13),
('Approach and Recover Counter Clockwise - Top Left', 'Midfield 8', 11),
('Approach and Recover Counter Clockwise - Top Right', 'Midfield 8', 10),
('Ladder Drill - Icky Shuffle', 'Midfield 8', 6),
('Ladder Drill - One Foot In Each', 'Midfield 8', 3),
('Ladder Drill - Two Feet In Each - Left First', 'Midfield 8', 5),
('Ladder Drill - Two Feet in Each - Right First', 'Midfield 8', 4),
('Ladder Drill - Two In Two Out', 'Midfield 8', 7),
('Pipe Approaches - Approach and Backpedal', 'Midfield 12', 1),
('Pipe Approaches - Approach and Backpedal', 'Midfield 4', 7),
('Pipe Approaches - C Approach and Shuffle', 'Midfield 12', 2),
('Pipe Approaches - C Approach and Shuffle', 'Midfield 4', 8),
('Pipe Approaches - C Approach and Shuffle Drop Step', 'Midfield 12', 5),
('Pipe Approaches - C Approach Turn and Run', 'Midfield 12', 3),
('Pipe Approaches - C Approach Turn and Run', 'Midfield 4', 9),
('Pipe Approaches - C Approach Turn and Run Drop Step', 'Midfield 12', 4),
('Pipe Approaches - Left Foot Forward Retreat Steps', 'Midfield 4', 10),
('Pipe Approaches - Right Foot Forward Retreat Steps', 'Midfield 4', 11),
('Fast Break Defense - Cross Crease Rotation Drill', 'Midfield 12', 12),
('Fast Break Defense - Get Down The Back Pipe Rotation Drill', 'Midfield 12', 14),
('Fast Break Defense - Point Slide Drill', 'Midfield 12', 11),
('Fast Break Defense - Up The Hash Rotation Drill', 'Midfield 12', 13),
('Crease Slide Drill - Left Alley Dodge', 'Midfield 12', 10),
('On Ball Defense to Recover Drill', 'Midfield 12', 8),
('Right Alley Crease Slide Drill', 'Midfield 12', 9),
('High Crease - Back Pipe Cut Catch and Finish Drill', 'Midfield 3', 15),
('High Crease - Ball Cut Catch and Finish Drill', 'Midfield 3', 14),
('High Crease - Clear Through Cut Catch and Finish Drill', 'Midfield 3', 13),
('Low Crease - Up Field Cut Catch and Finish Drill', 'Midfield 3', 17),
('Extended Swat The Fly Drill', 'Midfield 10', 10),
('Extended Swat The Fly Drill', 'Midfield 6', 2),
('Extended Swat The Fly Drill', 'Midfield 5', 2),
('Extended Swat The Fly Drill', 'Midfield 2', 8),
('Extended Swat The Fly Drill', 'Midfield 1', 10),
('Paint The Pipe Drill', 'Midfield 10', 3),
('Punch and Pull Passing Drill', 'Midfield 1', 8),
('Step Away Passing Drill', 'Midfield 1', 5),
('Swat The Fly Drill - Behind The Goal', 'Midfield 11', 1),
('Swat The Fly Drill - Behind The Goal', 'Midfield 9', 1),
('Swat The Fly Drill - Behind The Goal', 'Midfield 7', 3),
('Swat The Fly Drill - Behind The Goal', 'Midfield 6', 1),
('Swat The Fly Drill - Behind The Goal', 'Midfield 5', 1),
('Swat The Fly Drill - Behind The Goal', 'Midfield 2', 1),
('Swat The Fly Drill - Behind The Goal', 'Midfield 1', 9),
('Explode Speed Change Hesitation Drill', 'Midfield 9', 6),
('Rocker to Roll Dodge Drill', 'Midfield 9', 10),
('Rocker to Roll Dodge Drill', 'Midfield 5', 14),
('Skip Step Hesitation Drill', 'Midfield 9', 7),
('Step Away ReAttack Drill', 'Midfield 9', 8),
('True Rocker Drill', 'Midfield 9', 9),
('True Rocker Drill', 'Midfield 5', 12),
('3 Step Face Dodge to Roll Dodge Drill', 'Midfield 5', 15),
('Cross Over Step Roll Dodge to Shot on the Run Drill', 'Midfield 5', 13),
('Sell the Shot Roll Dodge Drill', 'Midfield 9', 14),
('Stick Away Turn and Switch Hands Drill', 'Midfield 1', 13),
('Jump Shot on the Run Drill', 'Midfield 11', 5),
('Jump Shot on the Run Drill', 'Midfield 3', 16),
('Matt Brown Shooting Drill', 'Midfield 11', 2),
('Matt Brown Shooting Drill', 'Midfield 7', 4),
('Matt Brown Shooting Drill', 'Midfield 5', 3),
('Matt Brown Shooting Drill', 'Midfield 2', 2),
('Richmond Step and Shoot on the Run Drill', 'Midfield 11', 4),
('Richmond Step and Shoot on the Run Drill', 'Midfield 7', 6),
('Richmond Step and Shoot on the Run Drill', 'Midfield 5', 4),
('Richmond Step and Shoot on the Run Drill', 'Midfield 2', 4),
('Shooting on the Run Around a Curve Drill - Across The Top', 'Midfield 11', 7),
('Shooting on the Run Around a Curve Drill - Across The Top', 'Midfield 7', 9),
('Shooting on the Run Around a Curve Drill - Across The Top', 'Midfield 5', 5),
('Shooting on the Run Around a Curve Drill - Across The Top', 'Midfield 2', 6),
('Shooting on the Run Around a Curve Drill - Down The Alley', 'Midfield 11', 3),
('Shooting on the Run Around a Curve Drill - Down The Alley', 'Midfield 7', 5),
('Shooting on the Run Around a Curve Drill - Down The Alley', 'Midfield 2', 3),
('Shooting on the Run Around a Curve Drill - Up The Hash / Turn The Corner', 'Midfield 11', 6),
('Shooting on the Run Around a Curve Drill - Up The Hash / Turn The Corner', 'Midfield 7', 8),
('Shooting on the Run Around a Curve Drill - Up The Hash / Turn The Corner', 'Midfield 5', 6),
('Shooting on the Run Around a Curve Drill - Up The Hash / Turn The Corner', 'Midfield 2', 7),
('T2 Shooting on the Run Footwork Drill', 'Midfield 2', 5),
('Answer Move to Time and Room - Time and Room Shooting Drill', 'Midfield 6', 13),
('Answer Move to Time and Room - Time and Room Shooting Drill', 'Midfield 2', 13),
('Catch Across Body - Time and Room Shooting Drill', 'Midfield 6', 6),
('Catch Across Body - Time and Room Shooting Drill', 'Midfield 2', 12),
('Pop to Shot - Time and Room Shooting Drill', 'Midfield 6', 5),
('Pop to Shot - Time and Room Shooting Drill', 'Midfield 5', 7),
('Pop to Shot - Time and Room Shooting Drill', 'Midfield 2', 11),
('Roll Dodge to Set Feet - Time and Room Shooting Drill', 'Midfield 9', 11),
('Roll Dodge to Set Feet - Time and Room Shooting Drill', 'Midfield 2', 14),
('Shuffle Step Time and Room Shooting Drill - Behind The Goal', 'Midfield 10', 8),
('Shuffle Step Time and Room Shooting Drill - Behind The Goal', 'Midfield 6', 3),
('Shuffle Step Time and Room Shooting Drill - Behind The Goal', 'Midfield 2', 9),
('Shuffle Step Time and Room Shooting Drill - Behind The Goal', 'Midfield 1', 11),
('Split to Set Feet - Time and Room Shooting Drill', 'Midfield 7', 11),
('Split to Set Feet - Time and Room Shooting Drill', 'Midfield 6', 4),
('Split to Set Feet - Time and Room Shooting Drill', 'Midfield 2', 10),
('Slide Em Down - 2 Jab Explode Over The Top Drill', 'Midfield 11', 12),
('Slide Em Down - 2 Jab Explode Over The Top Drill', 'Midfield 7', 16),
('Slide Em Down - Explode Over The Top Drill', 'Midfield 11', 11),
('Slide Em Down - Explode Over The Top Drill', 'Midfield 5', 11),
('Slide Em Down - Explode Underneath Drill', 'Midfield 11', 9),
('Slide Em Down - Explode Underneath Drill', 'Midfield 5', 10),
('Slide Em Down - Jab and Go Underneath Drill', 'Midfield 11', 10),
('Slide Em Down - Jab to Keep Em Honest Drill', 'Midfield 11', 8),
('Slide Em Up - 3 Step Split Underneath.', 'Midfield 11', 15),
('Slide Em Up - 3 Step Split Underneath.', 'Midfield 7', 17),
('Slide Em Up - Explode Over The Top', 'Midfield 11', 13),
('Slide Em Up - Explode Underneath Dodging Drill', 'Midfield 11', 14),
('Foot Fire 3 Step Split Dodge Drill', 'Midfield 8', 14),
('Foot Fire 3 Step Split Dodge Drill', 'Midfield 7', 14),
('Foot Fire Single Jab Split Dodge Drill', 'Midfield 7', 13),
('Quick Switches Hand Speed Drill', 'Midfield 7', 7),
('Single Jab Split Dodge Drill', 'Midfield 7', 12),
('Standing Switches - Up to Pass Drill', 'Midfield 7', 10),
('Standing Switches - Up to Pass Drill', 'Midfield 1', 3);

-- Update skills_academy_workouts with drill_ids arrays
-- This matches drill names and builds ordered arrays

DO $$
DECLARE
    workout_record RECORD;
    drill_ids_array INTEGER[];
BEGIN
    -- Process each workout
    FOR workout_record IN
        SELECT DISTINCT workout_name FROM drill_workout_mapping
    LOOP
        -- Build drill_ids array for this workout
        SELECT ARRAY_AGG(sad.id ORDER BY dwm.sequence_order)
        INTO drill_ids_array
        FROM drill_workout_mapping dwm
        JOIN skills_academy_drills sad ON LOWER(TRIM(sad.title)) = LOWER(TRIM(dwm.drill_name))
        WHERE dwm.workout_name = workout_record.workout_name;

        -- Update workout with drill_ids array (try multiple title matching strategies)
        UPDATE skills_academy_workouts
        SET drill_ids = drill_ids_array,
            updated_at = NOW()
        WHERE (
            LOWER(TRIM(title)) = LOWER(TRIM(workout_record.workout_name))
            OR LOWER(TRIM(title)) LIKE LOWER(TRIM(workout_record.workout_name)) || '%'
            OR LOWER(TRIM(workout_record.workout_name)) LIKE LOWER(TRIM(title)) || '%'
        );

        RAISE NOTICE 'Updated workout: % with % drills', workout_record.workout_name, array_length(drill_ids_array, 1);
    END LOOP;
END$$;

-- Clean up temporary table
DROP TABLE drill_workout_mapping;

-- Verification query
SELECT 
    title,
    workout_type,
    array_length(drill_ids, 1) as drill_count,
    drill_ids
FROM skills_academy_workouts
WHERE drill_ids IS NOT NULL AND array_length(drill_ids, 1) > 0
ORDER BY workout_type, title;

-- Success message
DO $$ 
BEGIN 
    RAISE NOTICE 'Drill-Workout Mapping Complete! 🚀';
    RAISE NOTICE 'Processed 34 workouts with drill mappings';
    RAISE NOTICE 'Total drill-workout relationships: 419';
    RAISE NOTICE 'Skills Academy workouts now contain actual drill sequences!';
END $$;